"""remove

Revision ID: a581a28a1d7b
Revises: 914dadea4354
Create Date: 2024-11-14 14:10:51.699737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a581a28a1d7b'
down_revision: Union[str, None] = '914dadea4354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'scope')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('scope', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
