"""add scope field

Revision ID: b04b9386c6fe
Revises: 4446f53dda40
Create Date: 2024-11-14 01:18:02.299218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b04b9386c6fe'
down_revision: Union[str, None] = '4446f53dda40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('scope', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'scope')
    # ### end Alembic commands ###
